# 投票に関する設定
vote:
  ticket_give_size: 1
  # 一回の投票時に配布するチケット数を指定できます。64個以上を指定すると、ストックできなくなります。
  afnw_item_size: 8
  # /afnw実行時に配布するアイテム数を指定できます。
  afnw_scaffold_size: 8
  # /afnw実行時に配布する足場ブロックを指定できます。
